[workspace]
authors = ["Michael Denker, Hideaki Shimazaki"]
channels = ["conda-forge"]
name = "shimazaki-state-space-analysis"
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --user --name anda-d2"

[dependencies]
python = ">=3.10,<3.14"
numpy = ">=1.24,<3"
matplotlib = ">=3.7,<4"
scipy = ">=1.10,<2"
ipykernel = ">=6,<8"
jupyterlab = ">=4,<5"
tqdm = ">=4.64,<5"

### Jupyter Lab Environment (pixi run jupyter) #############

[feature.jupyter.dependencies]
python = "3.13.*"

[feature.jupyter.pypi-dependencies]
jupyterlab = ">=4"

[feature.jupyter.tasks]
jupyter = "jupyter lab"

[environments.jupyter]
features = ["jupyter"]
no-default-feature = true

################################################